name = "LinearCombinations"
uuid = "67be3549-475c-46bf-8928-de3404d670d9"
authors = ["matthias314"]
version = "0.4.0"

[deps]
StructEqualHash = "8bd03d06-bfef-4aaf-8250-1a26cbb401bf"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1.10"
StructEqualHash = "0.1"
MacroTools = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
